name: Build Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone SonixQMK
        run: git clone https://github.com/SonixQMK/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ls keyboards
      - name: fix gcc
        run: cd qmk_firmware && ls keyboards/keychron
      - name: Install git submodules
        run: cd qmk_firmware && ls keyboards/keychron/k3
